---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - nodecleanupcontroller.gitlab.arc.hcloud.io
  resources:
  - nodecleanups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodecleanupcontroller.gitlab.arc.hcloud.io
  resources:
  - nodecleanups/finalizers
  verbs:
  - update
- apiGroups:
  - nodecleanupcontroller.gitlab.arc.hcloud.io
  resources:
  - nodecleanups/status
  verbs:
  - get
  - patch
  - update
